INSERT INTO VENUE (LEVEL_ID, LEVEL_NAME, PRICE, NUMBER_OF_ROWS, SEATS_IN_ROW) VALUES (1, 'Orchestra', 100.00, 25, 50);
INSERT INTO VENUE (LEVEL_ID, LEVEL_NAME, PRICE, NUMBER_OF_ROWS, SEATS_IN_ROW) VALUES (2, 'Main', 75.00, 20, 100);
INSERT INTO VENUE (LEVEL_ID, LEVEL_NAME, PRICE, NUMBER_OF_ROWS, SEATS_IN_ROW) VALUES (3, 'Balcony 1', 50.00, 15, 100);
INSERT INTO VENUE (LEVEL_ID, LEVEL_NAME, PRICE, NUMBER_OF_ROWS, SEATS_IN_ROW) VALUES (4, 'Balcony 2', 40.00, 15, 100);