CREATE TABLE VENUE (
  LEVEL_ID       NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
  LEVEL_NAME     VARCHAR(100)         NOT NULL,
  PRICE          DECIMAL              NOT NULL,
  NUMBER_OF_ROWS NUMERIC(12)          NOT NULL,
  SEATS_IN_ROW   NUMERIC(12)          NOT NULL
);

CREATE TABLE CUSTOMER (
  ID         NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
  EMAIL      VARCHAR(100)         NOT NULL
);

CREATE TABLE SEAT_HOLD (
  ID           NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
  CUSTOMER_ID  NUMERIC(12)          NOT NULL,
  HOLD_TIME    TIMESTAMP,
  BOOKING_CODE VARCHAR(40),
  BOOKING_TIME TIMESTAMP
);

CREATE TABLE SEAT_BOOKING (
  ID              NUMERIC(12) IDENTITY NOT NULL PRIMARY KEY,
  HOLD_ID         NUMERIC(12)          NOT NULL,
  LEVEL_ID        NUMERIC(12)          NOT NULL,
  NUMBER_OF_SEATS NUMERIC(12)          NOT NULL
);

ALTER TABLE CUSTOMER ADD CONSTRAINT "CUSTOMER_EMAIL_UQ" UNIQUE (EMAIL);
ALTER TABLE SEAT_HOLD ADD CONSTRAINT "CUSTOMER_SEAT_HOLD_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("ID");
ALTER TABLE SEAT_BOOKING ADD CONSTRAINT "SEAT_HOLD_FK" FOREIGN KEY ("HOLD_ID") REFERENCES "SEAT_HOLD" ("ID");
ALTER TABLE SEAT_BOOKING ADD CONSTRAINT "VENUE_BOOKING_FK" FOREIGN KEY ("LEVEL_ID") REFERENCES "VENUE" ("LEVEL_ID");